### ISSUE TITLE
Just Plain Confusion (I Have A Simple Fix For This Though)

### ISSUE THREAD

**Issue by SkylaDev** [NerexNX/GeometryPy#3]
The Actual Module Doesn't Work.

This Is Because In The __init__.py File In The Main GeometryPy File In All Of The Commands You Have Structured It As For Example: "result = GDPyCommands.GetUserInfo(accID, PrintReturn)" Which Will Return The Error: "TypeError: GetUserInfo() takes 1 positional argument but 2 were given".

To Fix This All You Need To Do Is Remove The "PrintReturn" In the Arguments And The Commands Work Again.

I Have Tried Doing This And The Module Works For Me.

Thanks For Reading.

And BTW, I Love This Module, Thanks For Making It.

**Comment by djebrilelfeddi** [comment]
Hello stshrewsburyDev! 

You're right! The old functions had a "PrintReturn" parameter but i forgot to remove it in the main file, i'm going to update it right now. 

Thanks for making this issue, have a good day!
(I'm happy that you like this module ^^)
