### ISSUE TITLE
Error while importing

### ISSUE THREAD

**Issue by RealistikDash** [NerexNX/GeometryPy#4]
I get this error when trying to Import it:
`  File "C:\Users\Relesto\Desktop\RealistikBot\realistikbotrewritebeta\GeometryPy\__init__.py", line 6, in <module>
    import GeometryPy.commands as GDPyCommands
  File "C:\Users\Relesto\Desktop\RealistikBot\realistikbotrewritebeta\GeometryPy\commands\__init__.py", line 13
    def GetUserInfo(str(User)):
                       ^
SyntaxError: invalid syntax`

I use python 3.6.5

**Comment by djebrilelfeddi** [comment]
Hello RealistikDash,
This issue should be fixed in the update i made right now.
Hope it work for you now.

**Comment by RealistikDash** [comment]
It imports fine now.
